server:
  port: 3003

spring:
  application:
    name: auth-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "https://zipkin.code-factory.co.kr/api/v2/spans"

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"