server:
  port: 3003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://eureka.code-factory.co.kr/eureka/

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://config.code-factory.co.kr
      request-connect-timeout: 5000 # 설정 서버에 연결될 때까지 기다리는 시간(밀리초)
      request-read-timeout: 5000 # 설정 서버에서 설정 데이터를 읽을 때까지 기다리는 시간(밀리초)
      fail-fast: true # 설정 서버 연결 실패를 치명적 오류로 인식
      retry:
        max-attempts: 6 # 시도의 최대 횟수
        initial-interval: 1000  # 최초 재시도 지연 시간(밀리초)
        max-interval: 2000 # 재시도 지연최대 시간(밀리초)
        multiplier: 1.1 #지연 시간 계산 승수

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "https://zipkin.code-factory.co.kr/api/v2/spans"

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

